export type HouseRoomHrid =
  | '/house_rooms/archery_range'
  | '/house_rooms/armory'
  | '/house_rooms/brewery'
  | '/house_rooms/dairy_barn'
  | '/house_rooms/dining_room'
  | '/house_rooms/dojo'
  | '/house_rooms/forge'
  | '/house_rooms/garden'
  | '/house_rooms/gym'
  | '/house_rooms/kitchen'
  | '/house_rooms/laboratory'
  | '/house_rooms/library'
  | '/house_rooms/log_shed'
  | '/house_rooms/mystical_study'
  | '/house_rooms/sewing_parlor'
  | '/house_rooms/workshop';
