import { CombatStyleHrid } from 'src/new/core/hrid/CombatStyleHrid';
import { DamageTypeHrid } from 'src/new/core/hrid/DamageTypeHrid';

export interface CombatStats {
  combatStyleHrids: null | CombatStyleHrid[];
  damageType: '' | DamageTypeHrid;
  attackInterval: number;
  castSpeed: number;
  abilityHaste: number;
  criticalRate: number;
  criticalDamage: number;
  stabAccuracy: number;
  slashAccuracy: number;
  smashAccuracy: number;
  rangedAccuracy: number;
  magicAccuracy: number;
  stabDamage: number;
  slashDamage: number;
  smashDamage: number;
  rangedDamage: number;
  magicDamage: number;
  taskDamage: number;
  physicalAmplify: number;
  waterAmplify: number;
  natureAmplify: number;
  fireAmplify: number;
  healingAmplify: number;
  armorPenetration: number;
  waterPenetration: number;
  naturePenetration: number;
  firePenetration: number;
  physicalReflectPower: number;
  maxHitpoints: number;
  maxManapoints: number;
  stabEvasion: number;
  slashEvasion: number;
  smashEvasion: number;
  rangedEvasion: number;
  magicEvasion: number;
  armor: number;
  waterResistance: number;
  natureResistance: number;
  fireResistance: number;
  tenacity: number;
  lifeSteal: number;
  manaLeech: number;
  HPRegen: number;
  MPRegen: number;
  combatDropRate: number;
  combatDropQuantity: number;
  combatRareFind: number;
  combatExperience: number;
  foodSlots: number;
  drinkSlots: number;
}
